PYTHON3 ?= python3

check:
	$(PYTHON3) ./test_single_commands.py
	$(PYTHON3) ./test_redirect.py
	$(PYTHON3) ./test_pipes_1.py
	$(PYTHON3) ./test_pipes_2.py
	$(PYTHON3) ./test_builtins.py
	$(PYTHON3) ./test_advanced.py
